### ISSUE TITLE
tempdir function in `./pants` doesn't work on osx

### ISSUE THREAD

**Issue by pgroudas** [pantsbuild/setup#1]
I don't think the `-p` option of `mktemp` is supported, as OSX ships with a BSD version of mktemp from 2005.

(I'll update this with a proposed OSX workaround if I find one)

**Comment by pgroudas** [comment]
similarly, `mv -T` is unsupported.

**Comment by mgadda** [comment]
Just bumped into: 

```bash
mv: illegal option -- T
```

Is there workaround?

**Comment by jsirois** [comment]
I think I fixed these 2 issues in https://github.com/pantsbuild/setup/commit/0397d549d36db84f83efcf5ed5903d00c0fa6f92

That said - this repo needs linux and OSX ci setup.  For those I've forked #2.
