### ISSUE TITLE
bootstrap script does not handle being run from outside of the repo root well

### ISSUE THREAD

**Issue by cburroughs** [pantsbuild/setup#10]
If the bootstrap script is run from outside the repo root (or wherever `pants.ini` is present) it will fallback to the `unspecified` version.  This will then cause a  Version mismatch exception when pants actually runs because pants will search for `pants.ini` at the root and finds it is supposed to be using a different version.

We can work around this locally with `git rev-parse --show-toplevel`/pants`but that's obviously a git specific solution and I'm unsure if there is a good path forward without re-writing the code for finding`pants.ini` in bash.

We run into this because humans run pants from scripts inside our repository (for example a local `fab.sh` that wraps fabric and the dependencies for this fabfile) and those scripts might be at an arbitrary location in the repo (we certainly don't want to stick a hundred bash scripts in the root).

**Comment by jsirois** [comment]
Well, this is old. I hit this as well trying to hermeticize an integration test that ran `./pants ...`, from a different directory than `./pants`. Since the script already assumes bash - there is a portable way to get the `./pants` parent dir robustly. I'll take a whack.
