### ISSUE TITLE
determine_default_python_exe should check the internal interpreter version instead of its executable name

### ISSUE THREAD

**Issue by Gerrit-K** [pantsbuild/setup#100]
I'm running python on macOS and have installed python3.9 as well as python3.8 using homebrew. The app I'm currently using pants for uses 3.8 whereas the default is now 3.9 (and many apps require that). Since I don't want to unlink and re-link 3.8 every time I do a brew upgrade, I keep 3.9 as the default and tried to setup my environment for said app to use a virtualenv with 3.8 instead.

For most tools & IDEs this was pretty easy, but the pants wrapper script doesn't seem to respect that version. Although `python` and `python3` link to the correct python3.8 binary (`/usr/local/Cellar/python@3.8/3.8.11/bin/python3`), the wrapper is hard coded to iterate through executables that are named `pythonX.X`. And since `virtualenv` doesn't create a link or shim in that format, I don't have a `python3.8` executable. I _do_ however have a `python3.9` executable (linked by homebrew), which then (wrongfully) becomes pants next best guess (despite having set `interpreter_constraints = ["==3.8.*"]`)*.

In my opinion, if `interpreter_search_paths = ["<PATH>"]` is set, pants should also consider `python` / `python3`, check their versions and see if they satisfy the configured constraints.  Moreover, it should rather check the _actual_ interpreter version instead of its bare name.

*I believe this might be a bug that is already resolved by now. The wrapper we're using was created sometime around pants 2.2 or 2.3

**Comment by benjyw** [comment]
Hi, sorry you're having trouble with this. 

Just to clarify, there are two different interpreter selections at work: 

- The `pants` runner script selects the interpreter that Pants itself runs on. 3.8 and 3.9 should both be fine for that.

- Then there is the interpreter Pants selects to run your code/tests against. That can be a different interpreter, even one that Pants cannot run itself on (such as 3.6 or even 2.7).  This is what `interpreter_constraints` applies to. And for this, just as you describe, Pants does check the actual interpreter version by running the interpreter and having it report its own version. It doesn't rely on naming. 

So, to be sure I understand, is the issue with the interpreter Pants is running on via this script? Or is it with Pants selecting the wrong interpreter to run your code on? E.g., your tests are failing because they are running on 3.9 instead of 3.8 or something like that? What is the phenomenon you're seeing that indicates an error in interpreter selection? 

Thanks for providing more info!

**Comment by Gerrit-K** [comment]
Hi @benjyw (and others), thanks for the quick reply! 

The distinguishment you're mentioning makes sense, and I'm pretty sure that the issue is related to the former interpreter, i.e. the one Pants itself is running with, because it never reached the actual testing phase but always crashed during bootstrapping. 

I've looked a bit deeper into this and am starting to believe that I misphrased the issue and didn't provide enough information. Let me try to make up for that. First off, a couple of facts:
* As stated above, I have `python@3.8` and `python@3.9` installed with homebrew, but only the latter is linked, which means that the default `/usr/local/bin/python3` links to 3.9
* I've set up a `virtualenv` with 3.8 and want Pants to use it. In my IDE (IntelliJ / PyCharm) I've configured it as the python SDK and in the shell I'm using `direnv` to set it up.
* Our repository is configured for (and contains the wrapper script from) Pants version `2.3.0`, so it's a bit outdated
* Running Pants from the shell works* (more on that later), but running it from the IDE (more specifically as a pre-commit hook in the git vcs integration of the IDE) didn't work

The error I was seeing in the IDE was:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0   1042      0 --:--:-- --:--:-- --:--:--  1042
100   281  100   281    0     0   1248      0 --:--:-- --:--:-- --:--:--  1248
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3626k  100 3626k    0     0  1434k      0  0:00:02  0:00:02 --:--:-- 1807k
Using base prefix '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9'
Traceback (most recent call last):
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 2567, in <module>
    main()
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 783, in main
    create_environment(
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 1071, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 1361, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 1254, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-16.4.3/virtualenv.py", line 1186, in change_prefix
    assert False, "Filename {} does not start with any of these prefixes: {}".format(filename, prefixes)
AssertionError: Filename /usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py does not start with any of these prefixes: ['/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Extras/lib/python', '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9', '/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9', '/Users/gerrit/Library/Python/3.9/lib/python/site-packages', '/Users/gerrit/.local/lib/python/3.9/site-packages', '/Users/gerrit/Library/Python/3.9/site-packages', '/Library/Python/3.9/site-packages']
./pants: line 263: /Users/gerrit/.cache/pants/setup/bootstrap-Darwin-x86_64/2.3.0_py39/bin/python: No such file or directory
```

When ran from the shell, I noticed this line:
```
Using base prefix '/usr/local/Cellar/python@3.8/3.8.11/bin/../Frameworks/Python.framework/Versions/3.8'
```
This led me to believe that the IDE somehow just used the wrong python version to bootstrap Pants, so I added a couple of debug logs to the commit hook to confirm that the IDE definitely has the correct `bin` directory from the virtualenv in its `PATH` variable. And indeed, `PATH` was correct and `python --version` yielded `3.8.11`. So I've started to analyze the bootstrapping script and realized that it was looking _exactly_ for `python3.8`, which didn't exist, and then fell back to `python3.9` instead of trying the obvious `python`. I thought it might be worth a try to update the script to the most recent version, but that simply changed the error message to:
```
No valid Python interpreter found. For `pants_version = "2.3.0"`, Pants requires Python 3.7 or 3.8 to run. Please check that a valid interpreter is installed and on your $PATH.
```
Then, I though, I might as well upgrade to a newer Pants version and tried `2.6.0`, only to be greeted with yet another error message - which I unfortunately didn't pay much attention to, because then I would've realized that it's related to one of our plugins, probably not being compatible with the new version. Instead, however, I neglected this idea and reverted back to `2.3.0`.

This was about the time when I reported this issue. Fast-forward to now. While I was starting to write this reply, I tried to reproduce the issue and stumbled upon a small but important line in my `.direnvrc` (right after the line that activates the `virtualenv`):
```
export PYTHON=$(command -v python3)
```
This was all along the reason why Pants worked on the command line, because if `PYTHON` is specified, the bootstrapping script uses this version instead of trying to find a matching one. I believe I've added this line a couple of months back when Pants didn't support python 3.9 yet and forgot about it. It now just emerged again when we've introduced the pre-commit hooks to our repo, which are also run from the IDE, which in turn does not have the direnv variables.

To summarize, this is now my assumption on what happened:
* The missing `PYTHON` variable forced my IDE to find a matching python version, prioritizing `python3.9` over `python`
* Pants 2.3.0 was not (yet) compatible with python 3.9, hence the first (and second) error (, probably?)
* Our plugins are not (yet) compatible with newer versions of Pants, but at the time of writing, I was misinterpreting this error as "not related", so I didn't look deeper into this and neglected the upgade

Although I think the "mystery" is solved now (and the issue can easily be mitigated by creating a link named `python3.8`, pointing to `python3`). I still think it would be nice if the wrapper script would try the obvious choice of `python` or `python3` when determining a matching interpreter.

Lastly, I'm sorry for the caused confusion (and also this wall of text 🙈 but I hope it helps retracing my thoughs)!

**Comment by benjyw** [comment]
Thanks for the great detective work! This is now very clear. 

This is more support for our desire to ship pants as a fully-linked binary that contains its own interpreter. See https://github.com/pantsbuild/pants/issues/7369 . 

Meanwhile, keep in mind that you are free to edit the `pants` script in your repo along the lines you suggest, if that is helpful. You don't have to keep it identical to the one from this repo. 

And it sounds like the problem will go away once you upgrade Pants to a version that can run on 3.9. It's probably a good idea to upgrade anyway, just to stay on top of the latest bugfixes and so on...

As for your suggestion of modifying this script to allow it to look for and run on `python3` as a last fallback - I'll leave that to the folks who know this area better than I do to comment on (and to whom this issue is assigned) as I'm not sure of the unintended consequences. 

Thanks again for the report!

**Comment by jsirois** [comment]
Some scattered thoughts:

@Gerrit-K re:
> I've set up a virtualenv with 3.8 and want Pants to use it.

Pants will not use it. At best it will use the interpreter found in it, but it will create its own venv under `~/.cache/pants/setup/<a dir>/<pants version>_py<python major minor version>/`

> *I believe this might be a bug that is already resolved by now. The wrapper we're using was created sometime around pants 2.2 or 2.3

Have you tried upgrading your `pants` script to the latest? It should work just fine with old Pants versions.

**Comment by Gerrit-K** [comment]
@jsirois thanks for your comments!

> Pants will not use it. At best it will use the interpreter found in it, but it will create its own venv under `~/.cache/pants/setup/<a dir>/<pants version>_py<python major minor version>/`

Good point, misphrased that. I wanted the Pants _bootstrapper_ to use it.

> Have you tried upgrading your pants script to the latest? It should work just fine with old Pants versions.

Yes, it did work - in the sense that it didn't raise the mentioned error. But instead it simply reported that our Pants version (2.3.0) is not compatible with the selected / detected Python version (3.9). However, I _did_ have a matching Python version at hand (3.8). It was just not to be found at `python3.8` but rather just `python`, because it was my virtualenv.

My point is that the wrapper script could be improved by checking the _actual version_ of the first `python` executable in the `PATH` instead of hard-coded looking for executables with the name `python3.8`, `python3.7`, `python3.6`, ... and so on, because they are not guaranteed to exist whereas a `python` executable is the bare minimum to run Pants, so it should always be there. If it's not compatible with Pants, it could still continue looking for other versions.

**Comment by jsirois** [comment]
Gotcha.
> whereas a python executable is the bare minimum to run Pants, so it should always be there. 

Ah - you're a bit naive there. I used to think this too, but some Debian distributions python3 packages only instal /usr/bin/python3 - no python!

> My point is that the wrapper script could be improved by checking the _actual version_ of the first python executable in the `PATH`...

Agreed.

**Comment by Gerrit-K** [comment]
> Ah - you're a bit naive there. I used to think this too, but some Debian distributions python3 packages only instal /usr/bin/python3 - no python!

Oh, didn't know that!

Thanks for addressing this so quickly 👍  I guess it's up to us now to update the script in our repo (and maybe Pants itself as well, while we're already at it ...)
