### ISSUE TITLE
Add interface to install deps from additional requirements.txt

### ISSUE THREAD

**Issue by mateor** [pantsbuild/setup#12]
I didn't realize that the install script had its own repo.

We use this script almost word-for-word in Fsq.io. The only change is that we [add a `FOURSQUARE_REQUIREMENTS`](https://github.com/foursquare/fsqio/blob/master/scripts/upkeep/opensource-tasks/opensource-pants-env.sh#L18) variable that points to an additional `requirements.txt`. We have added two lines to the install script so that it installs those python deps into the pants virtualenv.

Internally, we set up a whole additional virtualenv for our 3rdparty deps, called `fs-env`. From what I understand, that is what Twitter does as well and Square may be about to create their own. But maintaining that additional virtualenv is a lot to ask a user that may just want to add a couple python libraries.

Could we add the ability to pass additional `requirements.txt` to the install script? My first thought would be an environmental variable but perhaps there is a better idea. 

I am willing to write the patch if it (or something like it) sounds acceptable.

**Comment by jsirois** [comment]
Yes - this is definitely needed. Ideally though it would be handled by pants core since it already handles all bootstrapping of requirements for _plugins_.  The setup script here only bootstraps pants core - ie the `pantsbuild.pants` dist, no more - no less.

**Comment by benjyw** [comment]
Closing this as stale.
