### ISSUE TITLE
Add `bootstrap-update` command

### ISSUE THREAD

**Issue by kaos** [pantsbuild/setup#131]
The `bootstrap-update` command would fetch the latest setup script and save it over `$0`.

_Originally posted by @kaos in https://github.com/pantsbuild/setup/pull/129#discussion_r989356801_

**Comment by thejcannon** [comment]
FWIW We could always hardocde a "version" of the script in the script itself and in Pants. If they don't match, suggest an upgrade.

**Comment by thejcannon** [comment]
Oh thats literally https://github.com/pantsbuild/setup/pull/129

**Comment by kaos** [comment]
Superseded by `SCIE_BOOT=update pants`.
