### ISSUE TITLE
Add support for grabbing pants from a released pex.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/setup#27]
This could probably be done in a new setup script recommended to users over the old.
Released pexes are hosted on github: https://github.com/pantsbuild/pants/releases/tag/release_1.9.0.dev1

**Comment by huonw** [comment]
Pants has moved on significantly since this was filed. In particular, this setup repo is focused on getting the https://github.com/pantsbuild/scie-pants runner, which is what actually installs pants itself (and now happens to use a released PEX, too).
