### ISSUE TITLE
Try distributing the `pants` setup script as an sdist

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/setup#6]
As pointed out by @traviscrawford this might allow for a more seamless pants install.  For one, it ensures the user has python, if not python2.7.  For another, it could be a good way to keep the `pants` script from getting checked into each repo.

**Comment by benjyw** [comment]
Closing this as we now lean on [scie-pants](https://github.com/pantsbuild/scie-pants) to streamline pants installs, and are moving away from the `pants` setup script.
