### ISSUE TITLE
fix regression in pants wrapper due to virtualenv upgrade

### ISSUE THREAD

**Issue by tdyas** [pantsbuild/setup#94]
A regression was reported on the Pants Slack in the `./pants` wrapper script after a virtualenv upgrade. https://pantsbuild.slack.com/archives/C046T6T9U/p1608991742321800.

I reproduced it with the example-python repository:

```
~/TC/example-python$ ./pants --version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    606      0 --:--:-- --:--:-- --:--:--   610
100   281  100   281    0     0    747      0 --:--:-- --:--:-- --:--:--   747
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8861k  100 8861k    0     0  7348k      0  0:00:01  0:00:01 --:--:-- 14.2M
Traceback (most recent call last):
  File "/Users/tdyas/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-20.2.2/src/virtualenv/__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "/Users/tdyas/.cache/pants/setup/bootstrap-Darwin-x86_64/virtualenv-20.2.2/src/virtualenv/__main__.py", line 58, in run_with_catch
    from virtualenv.config.cli.parser import VirtualEnvOptions
ModuleNotFoundError: No module named 'virtualenv'
./pants: line 293: /Users/tdyas/.cache/pants/setup/bootstrap-Darwin-x86_64/2.0.0rc1_py38/bin/python: No such file or directory
```

We should revert until a solution is found. https://github.com/pantsbuild/setup/pull/93 has the reversion.

**Comment by tdyas** [comment]
Idea: Given Pants is Python 3.x only for its own execution, the `./pants` wrapper should just use the built-in `venv` module and not use `virtualenv` at all any more.

cc @stuhood @Eric-Arellano

**Comment by signal-alesieur** [comment]
Hi!
I think I'm hitting this problem inside one of my docker containers.
Is the latest workaround still to revert the pants wrapper?
Thanks!

**Comment by Eric-Arellano** [comment]
Hey @signal-alesieur, try using https://github.com/pantsbuild/setup/blob/gh-pages/pants. Tom reverted the virtualenv upgrade already in https://github.com/pantsbuild/setup/pull/93. However, users have to manually update this script whenever there is a change, so your script may be stale.

Let us know if you're still having this issue!

**Comment by signal-alesieur** [comment]
> Hey @signal-alesieur, try using https://github.com/pantsbuild/setup/blob/gh-pages/pants. Tom reverted the virtualenv upgrade already in #93. However, users have to manually update this script whenever there is a change, so your script may be stale.
> 
> Let us know if you're still having this issue!

Yup I'm working on doing the revert locally. I was just making sure there wasn't a best solution available that I missed :-) Thanks!

[EDIT] I didn't want to add another comment and "spam". But I can confirm that this change solved the issue for me. Thanks!
